name: qqq
root: <%= Dir.pwd %>

on_project_start: cd qqq-gem ; rake install

windows:
  - test:
      layout: main-horizontal
      panes:
        - qqq echo "Hello, world\!"
        - qqq tail
        - qqq payload
        - qqq send

  - server:
      layout: tiled
      panes:
        - cd qqq-frontend ; yarn serve
        - cd qqq-app; bundle exec rails s
        - cd qqq-app; tail -f log/development.log
        - open http://localhost:3600/messages http://localhost:8080/
