name: qqq
root: <%= Dir.pwd %>

# on_project_start: cd qqq-gem ; rake install

windows:

  # Me at work, I just want to see the thing in one place.
  - qqq_developer_user:
      root: <%= "#{Dir.pwd}/qqq-gem" %>
      layout: tiled
      panes:
        - bundle exec qqq mark 3
        - bundle exec qqq tail
  - file_appender:
      root: <%= "#{Dir.pwd}/qqq-gem" %>
      layout: tiled
      panes:
        - bundle exec qqq file-appender
        - bundle exec qqq filetail
      
  # - server:
  #     layout: tiled
  #     panes:
  #       - cd qqq-frontend ; yarn serve
  #       - cd qqq-app; bundle exec rails s
  #       - cd qqq-app; tail -f log/development.log
  #       - open http://localhost:3600/ http://localhost:8080/
